---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=110
      - TZ=Europe/London
    volumes:
      - /mnt/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
