---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=110
      - TZ=Europe/London
    volumes:
      - /mnt/radarr:/config
      - /mnt/plex/movies:/movies #optional
      - /mnt/download/complete:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
